//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute("ReplayIndex.xml", Namespace = "", IsNullable = false)]
//[System.Xml.Serialization.XmlRootAttribute("ReplayIndex", Namespace = "", IsNullable = false)]
//[System.Xml.Serialization.XmlRootAttribute("ReplayIndexFile", Namespace = "", IsNullable = false)]
public partial class ReplayIndexxml {
    
    private ReplayIndexxmlMatches[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Matches", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ReplayIndexxmlMatches[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute("ReplayIndexFile", Namespace = "", IsNullable = false)]
public partial class ReplayIndexOldFormat:ReplayIndexxml
{

    
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute("ReplayIndex", Namespace = "", IsNullable = false)]
public partial class ReplayIndexOldFormatV2 : ReplayIndexxml
{

  
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReplayIndexxmlMatches {

    private ReplayIndexxmlMatchesMatchRecord[] matchRecordField;
    private ReplayIndexxmlMatchesMatchRecord[] rowMatchRecordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MatchRecord", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ReplayIndexxmlMatchesMatchRecord[] MatchRecord {
        get {
            return this.matchRecordField;
        }
        set {
            this.matchRecordField = value;
        }
    }

    [System.Xml.Serialization.XmlElementAttribute("RowMatchRecord", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ReplayIndexxmlMatchesMatchRecord[] RowMatchRecord
    {
        get
        {
            return this.rowMatchRecordField;
        }
        set
        {
            this.rowMatchRecordField = value;
        }
    }

   
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReplayIndexxmlMatchesMatchRecord {
    
    private string homeInflictedInjuriesField;
    
    private string teamAwayLogoField;
    
    private string awayCashEarnedBeforeConcessionField;
    
    private string ratingField;
    
    private string idReplayStorageField;
    
    private string homeOccupationOwnField;
    
    private string awaySustainedKOField;
    
    private string awayInflictedInjuriesField;
    
    private string homeSustainedDeadField;
    
    private string clientVersionField;
    
    private string awayValueField;
    
    private string structStadiumField;
    
    private string matchUUIDField;
    
    private string coachAwayNameField;
    
    private string idCoachHomeField;
    
    private string replayFileNameField;
    
    private string homeInflictedInterceptionsField;
    
    private string awayWinningsDiceField;
    
    private string idCompetitionTypesField;
    
    private string homeScoreField;
    
    private string idCoachAwayCompletionStatusField;
    
    private string awayInflictedTacklesField;
    
    private string homeCoachCyanEarnedField;
    
    private string competitionRoundField;
    
    private string awayInflictedPassesField;
    
    private string homePossessionBallField;
    
    private string awayOccupationOwnField;
    
    private string homeCashBeforeMatchField;
    
    private string idMatchCompletionStatusField;
    
    private string coachHomeNameField;
    
    private string idTeamListingHomeField;
    
    private string homeCashSpentInducementsField;
    
    private string awayInflictedCasualtiesField;
    
    private string homeInflictedCatchesField;
    
    private string homePopularityBeforeMatchField;
    
    private string homeInflictedMetersPassingField;
    
    private string officialLeagueField;
    
    private string idMatchTypeField;
    
    private string homeOccupationTheirField;
    
    private string awayPopularityBeforeMatchField;
    
    private string idLeagueField;
    
    private string automatchField;
    
    private string awaySustainedDeadField;
    
    private string homeCashEarnedBeforeConcessionField;
    
    private string awayInflictedMetersRunningField;
    
    private string rankedField;
    
    private string homeCoachXpEarnedField;
    
    private string idCoachAwayField;
    
    private string homeSustainedKOField;
    
    private string awayMVPField;
    
    private string homeMVPField;
    
    private string homePopularityGainField;
    
    private string homeInflictedMetersRunningField;
    
    private string idCompetitionField;
    
    private string idCoachHomeCompletionStatusField;
    
    private string idRacesAwayField;
    
    private string homeInflictedTouchdownsField;
    
    private string homeSustainedCasualtiesField;
    
    private string awaySpirallingExpensesField;
    
    private string awayCoachCyanEarnedField;
    
    private string statsCategoriesField;
    
    private string homeSustainedInjuriesField;
    
    private string stadiumField;
    
    private string awayInflictedDeadField;
    
    private string leagueNameField;
    
    private string awayPossessionBallField;
    
    private string awayInflictedInterceptionsField;
    
    private string idRacesHomeField;
    
    private string homeInflictedPassesField;
    
    private string homeInflictedTacklesField;
    
    private string homeCashEarnedField;
    
    private string startedField;
    
    private string homeSustainedExpulsionsField;
    
    private string homeInflictedCasualtiesField;
    
    private string awaySustainedExpulsionsField;
    
    private string finishedField;
    
    private string awayInflictedKOField;
    
    private string awayCashBeforeMatchField;
    
    private string nameStadiumField;
    
    private string replayMd5Field;
    
    private string homeWinningsDiceField;
    
    private string awayOccupationTheirField;
    
    private string teamHomeNameField;
    
    private string awayInflictedMetersPassingField;
    
    private string homeNbSupportersField;
    
    private string playedField;
    
    private string abstractField;
    
    private string competitionNameField;
    
    private string bestMatchesField;
    
    private string awayInflictedPushOutsField;
    
    private string teamAwayNameField;
    
    private string homeSpirallingExpensesField;
    
    private string homeValueField;
    
    private string teamHomeLogoField;
    
    private string awaySustainedInjuriesField;
    
    private string awayCoachXpEarnedField;
    
    private string homeInflictedDeadField;
    
    private string awaySustainedCasualtiesField;
    
    private string awayPopularityGainField;
    
    private string spectatorsField;
    
    private string awayCashSpentInducementsField;
    
    private string awayScoreField;
    
    private string rerolledField;
    
    private string idTeamListingAwayField;
    
    private string idField;
    
    private string homeInflictedKOField;
    
    private string awayNbSupportersField;
    
    private string awayCashEarnedField;
    
    private string awayInflictedCatchesField;
    
    private string awayInflictedTouchdownsField;
    
    private string levelStadiumField;
    
    private string homeInflictedPushOutsField;
    
    private ReplayIndexxmlMatchesMatchRecordShardedIdTeamListingAway[] shardedIdTeamListingAwayField;
    
    private ReplayIndexxmlMatchesMatchRecordShardedIdTeamListingHome[] shardedIdTeamListingHomeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeInflictedInjuries {
        get {
            return this.homeInflictedInjuriesField;
        }
        set {
            this.homeInflictedInjuriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TeamAwayLogo {
        get {
            return this.teamAwayLogoField;
        }
        set {
            this.teamAwayLogoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayCashEarnedBeforeConcession {
        get {
            return this.awayCashEarnedBeforeConcessionField;
        }
        set {
            this.awayCashEarnedBeforeConcessionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Rating {
        get {
            return this.ratingField;
        }
        set {
            this.ratingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdReplayStorage {
        get {
            return this.idReplayStorageField;
        }
        set {
            this.idReplayStorageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeOccupationOwn {
        get {
            return this.homeOccupationOwnField;
        }
        set {
            this.homeOccupationOwnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwaySustainedKO {
        get {
            return this.awaySustainedKOField;
        }
        set {
            this.awaySustainedKOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayInflictedInjuries {
        get {
            return this.awayInflictedInjuriesField;
        }
        set {
            this.awayInflictedInjuriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeSustainedDead {
        get {
            return this.homeSustainedDeadField;
        }
        set {
            this.homeSustainedDeadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ClientVersion {
        get {
            return this.clientVersionField;
        }
        set {
            this.clientVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayValue {
        get {
            return this.awayValueField;
        }
        set {
            this.awayValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StructStadium {
        get {
            return this.structStadiumField;
        }
        set {
            this.structStadiumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MatchUUID {
        get {
            return this.matchUUIDField;
        }
        set {
            this.matchUUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CoachAwayName {
        get {
            return this.coachAwayNameField;
        }
        set {
            this.coachAwayNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdCoachHome {
        get {
            return this.idCoachHomeField;
        }
        set {
            this.idCoachHomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReplayFileName {
        get {
            return this.replayFileNameField;
        }
        set {
            this.replayFileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeInflictedInterceptions {
        get {
            return this.homeInflictedInterceptionsField;
        }
        set {
            this.homeInflictedInterceptionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayWinningsDice {
        get {
            return this.awayWinningsDiceField;
        }
        set {
            this.awayWinningsDiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdCompetitionTypes {
        get {
            return this.idCompetitionTypesField;
        }
        set {
            this.idCompetitionTypesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeScore {
        get {
            return this.homeScoreField;
        }
        set {
            this.homeScoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdCoachAwayCompletionStatus {
        get {
            return this.idCoachAwayCompletionStatusField;
        }
        set {
            this.idCoachAwayCompletionStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayInflictedTackles {
        get {
            return this.awayInflictedTacklesField;
        }
        set {
            this.awayInflictedTacklesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeCoachCyanEarned {
        get {
            return this.homeCoachCyanEarnedField;
        }
        set {
            this.homeCoachCyanEarnedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CompetitionRound {
        get {
            return this.competitionRoundField;
        }
        set {
            this.competitionRoundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayInflictedPasses {
        get {
            return this.awayInflictedPassesField;
        }
        set {
            this.awayInflictedPassesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomePossessionBall {
        get {
            return this.homePossessionBallField;
        }
        set {
            this.homePossessionBallField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayOccupationOwn {
        get {
            return this.awayOccupationOwnField;
        }
        set {
            this.awayOccupationOwnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeCashBeforeMatch {
        get {
            return this.homeCashBeforeMatchField;
        }
        set {
            this.homeCashBeforeMatchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdMatchCompletionStatus {
        get {
            return this.idMatchCompletionStatusField;
        }
        set {
            this.idMatchCompletionStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CoachHomeName {
        get {
            return this.coachHomeNameField;
        }
        set {
            this.coachHomeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdTeamListingHome {
        get {
            return this.idTeamListingHomeField;
        }
        set {
            this.idTeamListingHomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeCashSpentInducements {
        get {
            return this.homeCashSpentInducementsField;
        }
        set {
            this.homeCashSpentInducementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayInflictedCasualties {
        get {
            return this.awayInflictedCasualtiesField;
        }
        set {
            this.awayInflictedCasualtiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeInflictedCatches {
        get {
            return this.homeInflictedCatchesField;
        }
        set {
            this.homeInflictedCatchesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomePopularityBeforeMatch {
        get {
            return this.homePopularityBeforeMatchField;
        }
        set {
            this.homePopularityBeforeMatchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeInflictedMetersPassing {
        get {
            return this.homeInflictedMetersPassingField;
        }
        set {
            this.homeInflictedMetersPassingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OfficialLeague {
        get {
            return this.officialLeagueField;
        }
        set {
            this.officialLeagueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdMatchType {
        get {
            return this.idMatchTypeField;
        }
        set {
            this.idMatchTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeOccupationTheir {
        get {
            return this.homeOccupationTheirField;
        }
        set {
            this.homeOccupationTheirField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayPopularityBeforeMatch {
        get {
            return this.awayPopularityBeforeMatchField;
        }
        set {
            this.awayPopularityBeforeMatchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdLeague {
        get {
            return this.idLeagueField;
        }
        set {
            this.idLeagueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Automatch {
        get {
            return this.automatchField;
        }
        set {
            this.automatchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwaySustainedDead {
        get {
            return this.awaySustainedDeadField;
        }
        set {
            this.awaySustainedDeadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeCashEarnedBeforeConcession {
        get {
            return this.homeCashEarnedBeforeConcessionField;
        }
        set {
            this.homeCashEarnedBeforeConcessionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayInflictedMetersRunning {
        get {
            return this.awayInflictedMetersRunningField;
        }
        set {
            this.awayInflictedMetersRunningField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Ranked {
        get {
            return this.rankedField;
        }
        set {
            this.rankedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeCoachXpEarned {
        get {
            return this.homeCoachXpEarnedField;
        }
        set {
            this.homeCoachXpEarnedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdCoachAway {
        get {
            return this.idCoachAwayField;
        }
        set {
            this.idCoachAwayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeSustainedKO {
        get {
            return this.homeSustainedKOField;
        }
        set {
            this.homeSustainedKOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayMVP {
        get {
            return this.awayMVPField;
        }
        set {
            this.awayMVPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeMVP {
        get {
            return this.homeMVPField;
        }
        set {
            this.homeMVPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomePopularityGain {
        get {
            return this.homePopularityGainField;
        }
        set {
            this.homePopularityGainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeInflictedMetersRunning {
        get {
            return this.homeInflictedMetersRunningField;
        }
        set {
            this.homeInflictedMetersRunningField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdCompetition {
        get {
            return this.idCompetitionField;
        }
        set {
            this.idCompetitionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdCoachHomeCompletionStatus {
        get {
            return this.idCoachHomeCompletionStatusField;
        }
        set {
            this.idCoachHomeCompletionStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdRacesAway {
        get {
            return this.idRacesAwayField;
        }
        set {
            this.idRacesAwayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeInflictedTouchdowns {
        get {
            return this.homeInflictedTouchdownsField;
        }
        set {
            this.homeInflictedTouchdownsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeSustainedCasualties {
        get {
            return this.homeSustainedCasualtiesField;
        }
        set {
            this.homeSustainedCasualtiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwaySpirallingExpenses {
        get {
            return this.awaySpirallingExpensesField;
        }
        set {
            this.awaySpirallingExpensesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayCoachCyanEarned {
        get {
            return this.awayCoachCyanEarnedField;
        }
        set {
            this.awayCoachCyanEarnedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StatsCategories {
        get {
            return this.statsCategoriesField;
        }
        set {
            this.statsCategoriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeSustainedInjuries {
        get {
            return this.homeSustainedInjuriesField;
        }
        set {
            this.homeSustainedInjuriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Stadium {
        get {
            return this.stadiumField;
        }
        set {
            this.stadiumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayInflictedDead {
        get {
            return this.awayInflictedDeadField;
        }
        set {
            this.awayInflictedDeadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LeagueName {
        get {
            return this.leagueNameField;
        }
        set {
            this.leagueNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayPossessionBall {
        get {
            return this.awayPossessionBallField;
        }
        set {
            this.awayPossessionBallField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayInflictedInterceptions {
        get {
            return this.awayInflictedInterceptionsField;
        }
        set {
            this.awayInflictedInterceptionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdRacesHome {
        get {
            return this.idRacesHomeField;
        }
        set {
            this.idRacesHomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeInflictedPasses {
        get {
            return this.homeInflictedPassesField;
        }
        set {
            this.homeInflictedPassesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeInflictedTackles {
        get {
            return this.homeInflictedTacklesField;
        }
        set {
            this.homeInflictedTacklesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeCashEarned {
        get {
            return this.homeCashEarnedField;
        }
        set {
            this.homeCashEarnedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Started {
        get {
            return this.startedField;
        }
        set {
            this.startedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeSustainedExpulsions {
        get {
            return this.homeSustainedExpulsionsField;
        }
        set {
            this.homeSustainedExpulsionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeInflictedCasualties {
        get {
            return this.homeInflictedCasualtiesField;
        }
        set {
            this.homeInflictedCasualtiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwaySustainedExpulsions {
        get {
            return this.awaySustainedExpulsionsField;
        }
        set {
            this.awaySustainedExpulsionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Finished {
        get {
            return this.finishedField;
        }
        set {
            this.finishedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayInflictedKO {
        get {
            return this.awayInflictedKOField;
        }
        set {
            this.awayInflictedKOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayCashBeforeMatch {
        get {
            return this.awayCashBeforeMatchField;
        }
        set {
            this.awayCashBeforeMatchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NameStadium {
        get {
            return this.nameStadiumField;
        }
        set {
            this.nameStadiumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReplayMd5 {
        get {
            return this.replayMd5Field;
        }
        set {
            this.replayMd5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeWinningsDice {
        get {
            return this.homeWinningsDiceField;
        }
        set {
            this.homeWinningsDiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayOccupationTheir {
        get {
            return this.awayOccupationTheirField;
        }
        set {
            this.awayOccupationTheirField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TeamHomeName {
        get {
            return this.teamHomeNameField;
        }
        set {
            this.teamHomeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayInflictedMetersPassing {
        get {
            return this.awayInflictedMetersPassingField;
        }
        set {
            this.awayInflictedMetersPassingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeNbSupporters {
        get {
            return this.homeNbSupportersField;
        }
        set {
            this.homeNbSupportersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Played {
        get {
            return this.playedField;
        }
        set {
            this.playedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Abstract {
        get {
            return this.abstractField;
        }
        set {
            this.abstractField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CompetitionName {
        get {
            return this.competitionNameField;
        }
        set {
            this.competitionNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BestMatches {
        get {
            return this.bestMatchesField;
        }
        set {
            this.bestMatchesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayInflictedPushOuts {
        get {
            return this.awayInflictedPushOutsField;
        }
        set {
            this.awayInflictedPushOutsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TeamAwayName {
        get {
            return this.teamAwayNameField;
        }
        set {
            this.teamAwayNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeSpirallingExpenses {
        get {
            return this.homeSpirallingExpensesField;
        }
        set {
            this.homeSpirallingExpensesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeValue {
        get {
            return this.homeValueField;
        }
        set {
            this.homeValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TeamHomeLogo {
        get {
            return this.teamHomeLogoField;
        }
        set {
            this.teamHomeLogoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwaySustainedInjuries {
        get {
            return this.awaySustainedInjuriesField;
        }
        set {
            this.awaySustainedInjuriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayCoachXpEarned {
        get {
            return this.awayCoachXpEarnedField;
        }
        set {
            this.awayCoachXpEarnedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeInflictedDead {
        get {
            return this.homeInflictedDeadField;
        }
        set {
            this.homeInflictedDeadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwaySustainedCasualties {
        get {
            return this.awaySustainedCasualtiesField;
        }
        set {
            this.awaySustainedCasualtiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayPopularityGain {
        get {
            return this.awayPopularityGainField;
        }
        set {
            this.awayPopularityGainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Spectators {
        get {
            return this.spectatorsField;
        }
        set {
            this.spectatorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayCashSpentInducements {
        get {
            return this.awayCashSpentInducementsField;
        }
        set {
            this.awayCashSpentInducementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayScore {
        get {
            return this.awayScoreField;
        }
        set {
            this.awayScoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Rerolled {
        get {
            return this.rerolledField;
        }
        set {
            this.rerolledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IdTeamListingAway {
        get {
            return this.idTeamListingAwayField;
        }
        set {
            this.idTeamListingAwayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeInflictedKO {
        get {
            return this.homeInflictedKOField;
        }
        set {
            this.homeInflictedKOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayNbSupporters {
        get {
            return this.awayNbSupportersField;
        }
        set {
            this.awayNbSupportersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayCashEarned {
        get {
            return this.awayCashEarnedField;
        }
        set {
            this.awayCashEarnedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayInflictedCatches {
        get {
            return this.awayInflictedCatchesField;
        }
        set {
            this.awayInflictedCatchesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AwayInflictedTouchdowns {
        get {
            return this.awayInflictedTouchdownsField;
        }
        set {
            this.awayInflictedTouchdownsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LevelStadium {
        get {
            return this.levelStadiumField;
        }
        set {
            this.levelStadiumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeInflictedPushOuts {
        get {
            return this.homeInflictedPushOutsField;
        }
        set {
            this.homeInflictedPushOutsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ShardedIdTeamListingAway", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ReplayIndexxmlMatchesMatchRecordShardedIdTeamListingAway[] ShardedIdTeamListingAway {
        get {
            return this.shardedIdTeamListingAwayField;
        }
        set {
            this.shardedIdTeamListingAwayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ShardedIdTeamListingHome", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ReplayIndexxmlMatchesMatchRecordShardedIdTeamListingHome[] ShardedIdTeamListingHome {
        get {
            return this.shardedIdTeamListingHomeField;
        }
        set {
            this.shardedIdTeamListingHomeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReplayIndexxmlMatchesMatchRecordShardedIdTeamListingAway {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReplayIndexxmlMatchesMatchRecordShardedIdTeamListingHome {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
